modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/ShayBox/Durability101/issues"
[[mods]]
modId="durability101"
version="0.0.4"
displayName="Durability101"
displayURL="https://shaybox.com"
credits="Credit to RedBanHammer"
authors="ShayBox"
description='''
A rewrite of the original Durability101 mod
'''